version: '3.7'

services:

  redis:
    image: redis
    container_name: ginekolog-chat-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - ginekolog-network

networks:
  ginekolog-network:
